language: elixir

sudo: false

otp_release: '22.0'
elixir: '1.9'

stages:
  - check formatted
  - check outdated certdata
  - test

jobs:
  include:
    - stage: test
      script: mix test --trace

    - otp_release: '18.3'
      elixir: '1.1'

    - otp_release: '21.3'
      elixir: '1.8'

    - stage: check formatted
      script: mix format --check-formatted

    - stage: check outdated certdata
      script: mix certdata --check-outdated
      if: type = cron
